services:
  db:
    restart: always
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - coffe-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}"]
      retries: 20
      timeout: 3s
      interval: 2s

  backend:
    restart: always
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./Backend/code:/Backend/code
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      # For quick local testing we can force SQLite so backend doesn't block on Postgres.
      # Set to 'sqlite' to use the sqlite fallback in settings.py. Change back to 'postgresql' when ready.
      DATABASE_ENGINE: sqlite
      DATABASE_HOST: ""
      BACKEND_PORT: ${BACKEND_PORT}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER: ${DJANGO_SUPERUSER}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      USE_GUNICORN: ${USE_GUNICORN:-0}
    networks:
      - coffe-network

volumes:
  db:
    name: db

networks:
  coffe-network:
    driver: bridge