# Generated by Django 5.2.7 on 2025-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_center', models.CharField()),
                ('accesibility', models.CharField()),
                ('Name', models.CharField()),
                ('city', models.CharField()),
                ('city_district', models.CharField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population_in_district', models.IntegerField()),
                ('street', models.CharField()),
                ('is_suggested', models.BooleanField(default=False)),
            ],
        ),
    ]
